"""initial schema

Revision ID: 8a13c693bb81
Revises: 
Create Date: 2025-09-02 20:28:02.474057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a13c693bb81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('base_unit', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('package_head',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'shipped', name='package_status'), nullable=False),
    sa.Column('shipment_number', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_head',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'shipped', name='shipment_status'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_line',
    sa.Column('package_no', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_packageline_qty_pos'),
    sa.ForeignKeyConstraint(['item_no'], ['item.id'], ),
    sa.ForeignKeyConstraint(['package_no'], ['package_head.id'], ),
    sa.PrimaryKeyConstraint('package_no', 'line_no'),
    sa.UniqueConstraint('package_no', 'item_no', name='uq_packageline_pkg_item')
    )
    op.create_table('shipment_line',
    sa.Column('shipment_no', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('package_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_no'], ['package_head.id'], ),
    sa.ForeignKeyConstraint(['shipment_no'], ['shipment_head.id'], ),
    sa.PrimaryKeyConstraint('shipment_no', 'line_no'),
    sa.UniqueConstraint('package_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_line')
    op.drop_table('package_line')
    op.drop_table('shipment_head')
    op.drop_table('package_head')
    op.drop_table('user')
    op.drop_table('item')
    # ### end Alembic commands ###
