"""add packed status + stock table

Revision ID: d04069ca5a9c
Revises: ea8877404861
Create Date: 2025-09-07 19:50:12.636227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04069ca5a9c'
down_revision = 'ea8877404861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) alter enum for package_head.status
    with op.batch_alter_table("package_head", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum("open", "shipped", name="package_status"),
            type_=sa.Enum("open", "packed", "shipped", name="package_status"),
            existing_nullable=False
        )

    # 2) create stock table
    op.create_table(
        "stock",
        sa.Column("item_id", sa.Integer(), sa.ForeignKey("item.id"), primary_key=True),
        sa.Column("quantity_on_hand", sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # drop stock
    op.drop_table("stock")

    # revert enum
    with op.batch_alter_table("package_head", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum("open", "packed", "shipped", name="package_status"),
            type_=sa.Enum("open", "shipped", name="package_status"),
            existing_nullable=False
        )
    # ### end Alembic commands ###
